use anyhow::Result;
use union_code::{CompressedIntent, UnionCode};
use dualcache_ff::static_cache::static_cache::StaticDualCache;
use dualcache_ff::config::Config;
use serde_json::Value;

/// The core routing trait for resolving intents.
pub trait IntentRouter {
    /// Routes the incoming byte stream to a deterministic CompressedIntent and dynamic parameters.
    /// Returns Err(0x06) if the intent is not recognized and should fall back.
    fn route(&self, input: &[u8]) -> Result<(CompressedIntent, Option<Value>), u8>;
}

/// The ultra-fast L0 engine using UnionCode.
pub struct UnionCodeEngine<'a> {
    uc: UnionCode<'a, StaticDualCache<u32, CompressedIntent, 64>>,
}

impl<'a> UnionCodeEngine<'a> {
    pub fn new() -> Self {
        // We use a small memory footprint static dual cache for embedded/high-perf.
        let config = Config::with_memory_budget(1, 100);
        let cache = StaticDualCache::<u32, CompressedIntent, 64>::new(config);
        
        Self {
            uc: UnionCode::new(cache),
        }
    }
}

impl<'a> IntentRouter for UnionCodeEngine<'a> {
    #[inline(always)]
    fn route(&self, input: &[u8]) -> Result<(CompressedIntent, Option<Value>), u8> {
        self.uc.decode(input).map(|i| (i, None))
    }
}

use std::process::{Command, Stdio};
use std::io::{Write, BufReader, BufRead};
use std::sync::Mutex;

use vec101::engine::Vec101Engine;

/// The intelligent L1 fallback engine powered natively by vec101 Zero-Copy Engine
pub struct Vec101FallbackEngine {
    engine: Mutex<Option<Vec101Engine>>,
}

impl Vec101FallbackEngine {
    pub fn new() -> Self {
        println!("[Vec101FallbackEngine] Spawning native Rust 1bitLLM engine...");
        
        // Use the native Rust engine instead of python bridge
        let engine = Vec101Engine::new("../vec101/tools/bitnet_compiled.rkyv").ok();

        Self {
            engine: Mutex::new(engine),
        }
    }
}

impl IntentRouter for Vec101FallbackEngine {
    fn route(&self, input: &[u8]) -> Result<(CompressedIntent, Option<Value>), u8> {
        let input_str = String::from_utf8_lossy(input);
        println!("\n[L1 Fallback] UnionCode L0 Missed. Waking up native vec101 to analyze: {}", input_str);

        let mut lock = self.engine.lock().unwrap();
        if let Some(engine) = lock.as_mut() {
            // Use native generate_parallel (with batch_size = 1)
            let prompts = vec![input_str.to_string()];
            let _results = engine.generate_parallel(&prompts);
            
            // Mocking the result of intent recognition for demonstration
            println!("[1bitLLM Native] Recognized fallback intent using zero-copy execution");
            return Ok((CompressedIntent { opcode: 0x99, payload_id: 0x1234 }, None));
        }

        Err(0x06)
    }
}

impl Vec101FallbackEngine {
    pub fn generate_script(&self, prompt_text: &str) -> Result<String, String> {
        let mut lock = self.engine.lock().unwrap();
        if let Some(engine) = lock.as_mut() {
            let prompts = vec![prompt_text.to_string()];
            let results = engine.generate_parallel(&prompts);
            
            if let Some(script) = results.first() {
                return Ok(format!("# Generated by Native Vec101\n{}", script));
            }
        }
        Err("Failed to communicate with native engine".to_string())
    }

    pub fn generate_parallel(&self, prompts: &[String]) -> Result<Vec<String>, String> {
        let mut lock = self.engine.lock().unwrap();
        if let Some(engine) = lock.as_mut() {
            return Ok(engine.generate_parallel(prompts));
        }
        Err("Failed to communicate with native engine".to_string())
    }
}

use std::sync::OnceLock;

static FALLBACK_ENGINE: OnceLock<Vec101FallbackEngine> = OnceLock::new();

pub fn get_fallback_engine() -> &'static Vec101FallbackEngine {
    FALLBACK_ENGINE.get_or_init(|| Vec101FallbackEngine::new())
}

/// The Hybrid Router unifying L0 and L1
pub struct HybridRouter<'a> {
    fast_path: UnionCodeEngine<'a>,
}

impl<'a> HybridRouter<'a> {
    pub fn new() -> Self {
        Self {
            fast_path: UnionCodeEngine::new(),
        }
    }
}

impl<'a> IntentRouter for HybridRouter<'a> {
    #[inline(always)]
    fn route(&self, input: &[u8]) -> Result<(CompressedIntent, Option<Value>), u8> {
        match self.fast_path.route(input) {
            Ok(intent) => Ok(intent), // 28ns ~ 148ns execution
            Err(0x06) => get_fallback_engine().route(input), // Fallback to LLM execution
            Err(e) => Err(e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_union_code_engine_route() {
        let engine = UnionCodeEngine::new();
        
        // Test basic valid route that should be handled by the fast path (FST / Cache)
        let result = engine.route("請幫我拿咖啡".as_bytes());
        assert_eq!(
            result,
            Ok((CompressedIntent { opcode: 0x20, payload_id: 0x0A42 }, None))
        );
        
        // Test fallback error for unmapped intents
        let miss_result = engine.route("一個完全沒有見過的未知指令".as_bytes());
        assert_eq!(miss_result, Err(0x06)); // 0x06 is NotFound
    }
}
